### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by madvas** [district0x/hegex#13]
- [x] Section headlines such as "My Option Contracts" should be larger font size
- [x] Inputs should have white background color
- [x] In "NFT" column, we can display either just token id or "None". Remove "Yes"
- [x] Icon in select boxes is a bit too much off the center
![image](https://user-images.githubusercontent.com/3857155/114542859-b99c1080-9c58-11eb-9eb5-e097e07fe66c.png)
- [x] In "NFT" column, we can display either just token id or "None". Remove "Yes"
- [ ] Seems like in designs, there are 3 different font families used, for headlines, table text and buttons. Please try to implement the same way.
- [ ] Lines decoration on buttons is a bit thicker in designs. Also, when hovering, the lines effect should change color to white (in day mode)
![image](https://user-images.githubusercontent.com/3857155/114543045-f6680780-9c58-11eb-9358-ea15925b8adc.png)
- [x] Let's center WETH section to the middle
![image](https://user-images.githubusercontent.com/3857155/114549569-74c8a780-9c61-11eb-9ecd-3465137d9918.png)
- [x] In night mode, the selected tab should have blue font color
![image](https://user-images.githubusercontent.com/3857155/114549657-9164df80-9c61-11eb-90cc-81a8f802bde6.png)
- [x] In night mode, icon in select boxes should be dark blue
![image](https://user-images.githubusercontent.com/3857155/114549814-c709c880-9c61-11eb-8d58-d9b164440b65.png)
- [x] In night mode, it's missing circle around "+". Also, font color of "About" should be different. 
![image](https://user-images.githubusercontent.com/3857155/114549957-f28cb300-9c61-11eb-9945-748f75317c18.png)

**Comment by st4cks1defl0w** [comment]
Checked it out, on it

**Comment by st4cks1defl0w** [comment]
Linked PR that addresses everything but  `Lines decoration on buttons is a bit thicker in designs. Also, when hovering, the lines effect should change color to white (in day mode)` and fonts as I'm gonna do that in a mobile optimization PR this week (after ganache), as it's closely related (buttons need to be bigger to accommodate thicker lines)
