### ISSUE TITLE
Loading indicator for Offer

### ISSUE THREAD

**Issue by madvas** [district0x/hegex#17]
![image](https://user-images.githubusercontent.com/3857155/115977975-c1d44400-a5a6-11eb-9772-41c88efd3eb0.png)

After user clicks Offer button and signs with MM, it doesn't really indicate that something's happening, yet it still takes short while until we see the offer at the bottom. Offer button should be in loading state when this is happening, can be styled same way as when waiting for tx confirmation.

**Comment by st4cks1defl0w** [comment]
Incoming, decided to split it from https://github.com/district0x/hegex/pull/19, turned out to be a bit more work than I thought bc it's a 0x event (hence can't be tracked/persisted etc. by our d0x in-house `tx-id` cljs lib as I do with other web3 events)
