### ISSUE TITLE
Buy button improvements

### ISSUE THREAD

**Issue by madvas** [district0x/hegex#28]
![image](https://user-images.githubusercontent.com/3857155/116772908-3f52f500-aa7c-11eb-8bef-875d431dcad3.png)

* [ ] Buy button doesn't display loading indicator while tx is processed
* [ ] Buy button should be disabled if user doesn't have enough WETH/WBTC balance. When I tried, Metamask didn't even display failure warning and tx eventually failed, so we don't want users to waste gas in such cases.

**Comment by st4cks1defl0w** [comment]
@madvas these issues were batch-closed automatically as they were linked to PR that was merged, feel free to reopen in case anything is amiss
