### ISSUE TITLE
Minting option size less than 1 throws revert

### ISSUE THREAD

**Issue by madvas** [district0x/hegex#32]
Option size 0.9

![image](https://user-images.githubusercontent.com/3857155/118582549-b6e38c80-b7bd-11eb-91b0-3db11730857b.png)

Option size 1

![image](https://user-images.githubusercontent.com/3857155/118582607-d24e9780-b7bd-11eb-9a96-57a92b9d8fb0.png)

**Comment by st4cks1defl0w** [comment]
Have to recheck but I think this is due to very low `fee` param in ropsten hegic eth pool contract, I think there's a condition like
 `require(fees < position size)`, but will recheck that size param hegex sends has valid decimals
