### ISSUE TITLE
Scrolling behaviour

### ISSUE THREAD

**Issue by madvas** [district0x/hegex#58]
Scrolling acts bit strange at the end of the page. 

![Jul-07-2021 15-02-05](https://user-images.githubusercontent.com/3857155/124814799-7211e180-df34-11eb-9bc9-026d03e36f2a.gif)

**Comment by st4cks1defl0w** [comment]
Looking into it 👍

**Comment by st4cks1defl0w** [comment]
@madvas  damn couldn't repro it :/ could pls share more specs/state? is that just an ordinary laptop or some tablet? do you remember any interactions with UX b4 this happened?

**Comment by st4cks1defl0w** [comment]
just by looking at the css layout can't quite see what can be causing these issues (clearly some kind of overflow-y problem)

**Comment by madvas** [comment]
I'm using Mac with Chrome. I think it might be because of native smooth scrolling MacOS provides.

**Comment by st4cks1defl0w** [comment]
@madvas still on it, no luck with chrome though, today will look whether pending tx affects scrolling somehow 🤔 couldn't find a way unfortunately to simulate macos scrolling (I'm on linuxz), on iOS scrolls are fine

Just to clarify, is that a one-time thing or persistent issue that you see every time? this will be useful when debugging with state.

**Comment by st4cks1defl0w** [comment]
Closing due to issue being caused by a browser extension
